language: objective-c
osx_image: xcode8.2
script:
 - xcodebuild test -project Example/RFIBANHelper.xcodeproj -scheme RFIBANHelper build test -destination platform='iOS Simulator,name=iPhone 7,OS=latest' | xcpretty --color
 - pod lib lint --quick
after_success:
  - bash <(curl -s https://codecov.io/bash)
