language: objective-c
osx_image: xcode11.3
cache:
- bundler
script:
- xcodebuild test -project Example/RFIBANHelper.xcodeproj -scheme RFIBANHelper build
  test -destination platform='iOS Simulator,name=iPhone 11,OS=latest'
- bundle exec pod lib lint --quick
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- gem install bundler
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
- carthage archive RFIBANHelper
deploy:
  provider: releases
  api_key:
    secure: HOt8FQHfUUTlXsMWpY98Z5iv4xg+glBszVJSBt1/LqD4EapnELgQQFqE7t3X5LnGir8f/y/mN+BeVtLyaNMCNlfg/30Zh81PFeJ3s7YOt2v0b27JTbJj+AEEWz7UBQaIObEIfU+KlUCVUpgTRedcNIJdoqmRRnRP5Rp+0yIyfx5jYPaj++0n4vtiBP5A5yeVDb5a21A+OZH6VXJMO/glmoECj3I7y8uvzY/iNSSjemM+fYdaMgBednITAoxW6nAZvtknhRJT86uCXTOEndYfWUa7MkOeMgMJVOP0rVXSda6gck1Z/d5dcatc5VqJw78+P2PSXFgiPcQhBrzupJWeV+Y3MSWAbryq/fwu7YyUjB/SwoGZ812ZQsS+NK1KCl5LrYPB4vwJ3SW4QygJyAPk7A83xa3stoc51TcZp1Wa72LhUEBhs/rW8hjDkJe0gvF58lEEQwLMs1PXrufw2dLLvWNOCJsfIvkEiOYfJcajr5RqD3bF3q1Hs4ESyk0bi15zo6WbjS35xX5AOM9LlZcIVo4l5WZPSWoYRKsVGm8eEGyvgK3D/0T6cmcjAFsrjrDLwIou8bvJWp5tTz+NE8UtQBIKxGtVeO7ZcXLQPyXMDngAMx7D0jVJxKtXauoShBCtXAhRyVCfhng+bXC3bPeUiw4zib85YPBAIECZ9rltqbU=
  file: RFIBANHelper.framework.zip
  skip_cleanup: true
  on:
    repo: readefries/IBAN-Helper
    tags: true
