# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  displayName: 'Install Bundler'
  inputs:
    targetType: 'inline'
    script: |
      gem install -v 1.17.3 bundler
- task: Bash@3
  displayName: 'Install and updage carthage'
  inputs:
    targetType: 'inline'
    script: |
      brew update
      brew outdated carthage || brew upgrade carthage
- task: Xcode@5
  displayName: 'Run unit tests'
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: 'Example/RFIBANHelper.xcodeproj'
    scheme: 'RFIBANHelper'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11'
    publishJUnitResults: true
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
- task: Bash@3
  displayName: 'Cocoapod lint'
  inputs:
    targetType: inline
    script: |
      bundle exec pod lib lint --quick
- task: Bash@3
  displayName: 'Build and archive for cartage'
  inputs:
    targetType: inline
    script: |
      carthage build --no-skip-current
      carthage archive RFIBANHelper