# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Install Bundler
      
      gem install bundler
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Install brew
      brew update
      brew outdated carthage || brew upgrade carthage
- task: Xcode@5
  inputs:
    actions: 'test'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'Example/RFIBANHelper.xcodeproj'
    scheme: 'RFIBANHelper'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11'
